Phosphorus: 1000
Janelite: 200
Ellendyte: 50
Sapphire: 400
Tungsten: 500
Jolixanine: 200
Corinthium: 100
Zinc: 250
# This option will provide increased debugging information in console when the server starts.
IncreasedDebugging: false